repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1 # Use the latest revision or specify a specific version
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --recursive,
          ]

  - repo: https://github.com/psf/black
    rev: 24.3.0 # Use the latest revision
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use the latest revision
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0 # Use the latest revision
    hooks:
      - id: flake8
        args: [--max-line-length=120]
